name: Test Unit

on:
  pull_request:
    branches: ['trunk']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.2'
      - run: npm ci
      - run: npm run test:cov
